### ISSUE TITLE
REQUEST: Static naming convention for the EvtxHussar executable

### ISSUE THREAD

**Issue by AndrewRathbun** [yarox24/EvtxHussar#2]
Hello,

I just made a KAPE Module for EvtxHussar. 

https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/EvtxHussar.mkape

Ideally, the binary would be `evtxhussar.exe` so the KAPE Module doesn't have to be updated every time new features/bug fixes are released. 

https://github.com/EricZimmerman/KapeFiles/blob/a6a8d079c87c2c298488dbb1c06e5d620b5b6f71/Modules/Apps/GitHub/EvtxHussar.mkape#L10

Also, not a huge Sabaton fan (mostly due to lack of experience with them) but I'm a fellow metalhead so I appreciate the Sabaton reference `\m/`

Andrew

**Comment by yarox24** [comment]
Hello,

Wow, I will be part of KAPE ;)

I created a new release with new file name and directory structure. If those changes won't be enough I will made any additional changes.

Jarek

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/EvtxHussar.mkape

Adjusted to match the new change. I really appreciate it! It helps keep things simple :)
